<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Coupon;
use App\Models\Product;
use App\Models\Setting;
use App\Models\Slider;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {

        User::create([
            'name' => 'Admin',
            'email' => 'admin@admin.com',
            'password' => Hash::make('admin123'),
            'role' => 'admin',
        ]);

        $user = User::create([
            'name' => 'Test User',
            'email' => 'user@user.com',
            'password' => Hash::make('user123'),
            'role' => 'user',
        ]);

        $electronics = Category::create([
            'parent_id' => 0,
            'title' => 'Electronics',
            'keywords' => 'electronics, gadgets, tech',
            'description' => 'All electronic products',
            'status' => true,
        ]);

        $phones = Category::create([
            'parent_id' => $electronics->id,
            'title' => 'Phones',
            'keywords' => 'phones, smartphones, mobile',
            'description' => 'Smartphones and mobile phones',
            'status' => true,
        ]);

        $laptops = Category::create([
            'parent_id' => $electronics->id,
            'title' => 'Laptops',
            'keywords' => 'laptops, notebooks, computers',
            'description' => 'Laptops and notebooks',
            'status' => true,
        ]);

        $clothing = Category::create([
            'parent_id' => 0,
            'title' => 'Clothing',
            'keywords' => 'clothing, fashion, apparel',
            'description' => 'Fashion and clothing',
            'status' => true,
        ]);

        $mensClothing = Category::create([
            'parent_id' => $clothing->id,
            'title' => "Men's Clothing",
            'keywords' => 'men, shirts, pants',
            'description' => "Men's fashion",
            'status' => true,
        ]);

        $accessories = Category::create([
            'parent_id' => 0,
            'title' => 'Accessories',
            'keywords' => 'accessories, bags, watches',
            'description' => 'Fashion accessories',
            'status' => true,
        ]);

        $homeKitchen = Category::create([
            'parent_id' => 0,
            'title' => 'Home & Kitchen',
            'keywords' => 'home, kitchen, appliances, decor',
            'description' => 'Home and kitchen appliances and products',
            'status' => true,
        ]);

        $adminUser = User::where('role', 'admin')->first();

        $products = [
            [
                'category_id' => $phones->id,
                'title' => 'iPhone 15 Pro',
                'keywords' => 'iphone, apple, smartphone',
                'description' => 'Latest iPhone with pro camera system',
                'detail' => 'The iPhone 15 Pro features a titanium design, A17 Pro chip, and a versatile pro camera system.',
                'image' => 'products/iphone_15_pro.png',
                'price' => 999.99,
                'stock' => 50,
                'minstock' => 5,
                'discount' => 0,
                'status' => true,
            ],
            [
                'category_id' => $phones->id,
                'title' => 'Samsung Galaxy S24',
                'keywords' => 'samsung, galaxy, android',
                'description' => 'Flagship Android smartphone',
                'detail' => 'Samsung Galaxy S24 with AI features and advanced camera system.',
                'image' => 'products/galaxy_s24.png',
                'price' => 849.99,
                'stock' => 40,
                'minstock' => 5,
                'discount' => 10,
                'status' => true,
            ],
            [
                'category_id' => $laptops->id,
                'title' => 'MacBook Pro 14"',
                'keywords' => 'macbook, apple, laptop',
                'description' => 'Professional laptop with M3 chip',
                'detail' => 'MacBook Pro with M3 chip delivers incredible performance for professionals.',
                'image' => 'products/macbook_pro.png',
                'price' => 1999.99,
                'stock' => 25,
                'minstock' => 3,
                'discount' => 5,
                'status' => true,
            ],
            [
                'category_id' => $laptops->id,
                'title' => 'Dell XPS 15',
                'keywords' => 'dell, xps, laptop, windows',
                'description' => 'Premium Windows laptop',
                'detail' => 'Dell XPS 15 with OLED display and Intel Core i9 processor.',
                'image' => 'products/dell_xps.png',
                'price' => 1799.99,
                'stock' => 20,
                'minstock' => 3,
                'discount' => 15,
                'status' => true,
            ],
            [
                'category_id' => $mensClothing->id,
                'title' => 'Classic White T-Shirt',
                'keywords' => 'tshirt, white, cotton, men',
                'description' => 'Premium cotton white t-shirt',
                'detail' => '100% organic cotton, comfortable fit for everyday wear.',
                'image' => 'products/white_tshirt.png',
                'price' => 29.99,
                'stock' => 100,
                'minstock' => 10,
                'discount' => 0,
                'status' => true,
            ],
            [
                'category_id' => $accessories->id,
                'title' => 'Leather Wallet',
                'keywords' => 'wallet, leather, accessories',
                'description' => 'Genuine leather slim wallet',
                'detail' => 'Slim genuine leather wallet with RFID blocking technology.',
                'image' => 'products/leather_wallet.png',
                'price' => 49.99,
                'stock' => 75,
                'minstock' => 10,
                'discount' => 20,
                'status' => true,
            ],
            [
                'category_id' => $electronics->id,
                'title' => 'Sony WH-1000XM5 Wireless Headphones',
                'keywords' => 'headphones, sony, wireless, audio',
                'description' => 'Industry-leading noise canceling headphones',
                'detail' => 'Sony WH-1000XM5 wireless headphones with dual processors, 8 microphones, and auto NC optimizer.',
                'image' => 'products/headphones.png',
                'price' => 349.99,
                'stock' => 30,
                'minstock' => 5,
                'discount' => 10,
                'status' => true,
            ],
            [
                'category_id' => $accessories->id,
                'title' => 'Apple Watch Series 9',
                'keywords' => 'apple, watch, smartwatch, fitness',
                'description' => 'Sleek premium fitness smartwatch',
                'detail' => 'Apple Watch Series 9 with powerful S9 chip, bright display, and advanced health sensors.',
                'image' => 'products/apple_watch.png',
                'price' => 399.00,
                'stock' => 20,
                'minstock' => 3,
                'discount' => 0,
                'status' => true,
            ],
            [
                'category_id' => $electronics->id,
                'title' => 'RGB Mechanical Gaming Keyboard',
                'keywords' => 'keyboard, mechanical, rgb, gaming',
                'description' => 'Wired mechanical gaming keyboard',
                'detail' => 'Premium mechanical keyboard with customizable RGB backlighting and tactile switches.',
                'image' => 'products/keyboard.png',
                'price' => 89.99,
                'stock' => 45,
                'minstock' => 5,
                'discount' => 15,
                'status' => true,
            ],
            [
                'category_id' => $clothing->id,
                'title' => 'UltraBoost Running Shoes',
                'keywords' => 'shoes, running, athletic, sports',
                'description' => 'Premium responsive running shoes',
                'detail' => 'A comfortable running shoe featuring responsive boost cushioning and lightweight design.',
                'image' => 'products/running_shoes.png',
                'price' => 159.99,
                'stock' => 60,
                'minstock' => 8,
                'discount' => 5,
                'status' => true,
            ],
            [
                'category_id' => $accessories->id,
                'title' => 'Waterproof Travel Backpack',
                'keywords' => 'backpack, travel, bag, waterproof',
                'description' => 'Durable travel laptop backpack',
                'detail' => 'Heavy-duty waterproof travel backpack with multiple compartments and laptop sleeve.',
                'image' => 'products/backpack.png',
                'price' => 69.99,
                'stock' => 40,
                'minstock' => 5,
                'discount' => 0,
                'status' => true,
            ],
            [
                'category_id' => $homeKitchen->id,
                'title' => 'Automatic Espresso Coffee Machine',
                'keywords' => 'coffee, espresso, machine, kitchen',
                'description' => 'Premium home espresso maker',
                'detail' => 'Automatic espresso machine with built-in milk frother and precision grinding.',
                'image' => 'products/coffee_machine.png',
                'price' => 499.99,
                'stock' => 15,
                'minstock' => 2,
                'discount' => 20,
                'status' => true,
            ],
            [
                'category_id' => $accessories->id,
                'title' => 'Smart Audio Sunglasses',
                'keywords' => 'sunglasses, smart, audio, tech',
                'description' => 'Modern smart audio sunglasses with open-ear speakers',
                'detail' => 'Listen to music and make hands-free calls while protecting your eyes with smart audio technology.',
                'image' => 'products/smart_sunglasses.png',
                'price' => 199.99,
                'stock' => 30,
                'minstock' => 3,
                'discount' => 10,
                'status' => true,
            ],
            [
                'category_id' => $electronics->id,
                'title' => '3-in-1 Wireless Charging Stand',
                'keywords' => 'charger, wireless, fast charging',
                'description' => 'Sleek multi-device fast wireless charger',
                'detail' => 'Charge your smartphone, smartwatch, and earbuds simultaneously on a single aesthetic stand.',
                'image' => 'products/wireless_charger.png',
                'price' => 49.99,
                'stock' => 80,
                'minstock' => 10,
                'discount' => 0,
                'status' => true,
            ],
            [
                'category_id' => $clothing->id,
                'title' => 'Waterproof Windbreaker Jacket',
                'keywords' => 'jacket, clothing, windbreaker, waterproof',
                'description' => 'Lightweight waterproof outdoor jacket',
                'detail' => 'A stylish and durable windbreaker featuring water-resistant fabric and adjustable hood.',
                'image' => 'products/windbreaker.png',
                'price' => 89.99,
                'stock' => 40,
                'minstock' => 5,
                'discount' => 15,
                'status' => true,
            ],
            [
                'category_id' => $homeKitchen->id,
                'title' => 'Digital Air Fryer',
                'keywords' => 'airfryer, kitchen, appliance, cooking',
                'description' => 'Large capacity digital touchscreen air fryer',
                'detail' => 'Cook healthy, crispy meals with 360-degree rapid heat circulation and easy touchscreen pre-sets.',
                'image' => 'products/air_fryer.png',
                'price' => 119.99,
                'stock' => 25,
                'minstock' => 4,
                'discount' => 5,
                'status' => true,
            ],
            [
                'category_id' => $phones->id,
                'title' => 'Google Pixel 8 Pro',
                'keywords' => 'pixel, google, android, phone',
                'description' => 'Flagship Google smartphone with advanced AI',
                'detail' => 'Features the Google Tensor G3 chip, a triple rear camera system, and cutting-edge Google AI features.',
                'image' => 'products/pixel_8_pro.png',
                'price' => 899.99,
                'stock' => 15,
                'minstock' => 2,
                'discount' => 0,
                'status' => true,
            ],
            [
                'category_id' => $laptops->id,
                'title' => 'Asus ROG Zephyrus G14',
                'keywords' => 'asus, rog, laptop, gaming',
                'description' => 'Ultra-portable premium gaming laptop',
                'detail' => 'High-performance gaming laptop with AMD Ryzen processor, NVIDIA GeForce graphics, and ROG Nebula display.',
                'image' => 'products/rog_zephyrus.png',
                'price' => 1599.99,
                'stock' => 10,
                'minstock' => 2,
                'discount' => 10,
                'status' => true,
            ],
            [
                'category_id' => $electronics->id,
                'title' => 'Wireless Gaming Mouse',
                'keywords' => 'mouse, gaming, wireless, rgb',
                'description' => 'Ergonomic wireless gaming mouse with RGB highlights',
                'detail' => 'High-precision wireless gaming mouse featuring ultra-fast response time, ergonomic grip, and customizable RGB zones.',
                'image' => 'products/gaming_mouse.png',
                'price' => 79.99,
                'stock' => 50,
                'minstock' => 5,
                'discount' => 10,
                'status' => true,
            ],
            [
                'category_id' => $accessories->id,
                'title' => 'Chronograph Wrist Watch',
                'keywords' => 'watch, wrist watch, chronograph, accessories',
                'description' => 'Minimalist chronograph wrist watch with leather strap',
                'detail' => 'Elegant and minimalist chronograph wrist watch featuring a stainless steel case and a premium black leather strap.',
                'image' => 'products/chronograph_watch.png',
                'price' => 149.99,
                'stock' => 15,
                'minstock' => 2,
                'discount' => 0,
                'status' => true,
            ],
            [
                'category_id' => $homeKitchen->id,
                'title' => 'Ergonomic Office Chair',
                'keywords' => 'chair, office, ergonomic, furniture',
                'description' => 'Comfortable ergonomic mesh office chair',
                'detail' => 'High-back ergonomic office chair with breathable mesh, adjustable lumbar support, and 3D armrests for ultimate comfort.',
                'image' => 'products/office_chair.png',
                'price' => 249.99,
                'stock' => 12,
                'minstock' => 2,
                'discount' => 15,
                'status' => true,
            ],
            [
                'category_id' => $clothing->id,
                'title' => 'Leather Chelsea Boots',
                'keywords' => 'boots, shoes, leather, clothing, fashion',
                'description' => 'Classic genuine leather Chelsea boots',
                'detail' => 'Premium genuine leather Chelsea boots with a comfortable elastic side panel and durable rubber sole.',
                'image' => 'products/chelsea_boots.png',
                'price' => 129.99,
                'stock' => 30,
                'minstock' => 4,
                'discount' => 5,
                'status' => true,
            ],
            [
                'category_id' => $electronics->id,
                'title' => 'Wireless Noise Canceling Earbuds',
                'keywords' => 'earbuds, noise canceling, wireless, audio',
                'description' => 'Premium noise canceling wireless earbuds',
                'detail' => 'Experience immersive, high-fidelity sound with advanced active noise cancellation and long-lasting battery life.',
                'image' => 'products/wireless_earbuds.png',
                'price' => 129.99,
                'stock' => 50,
                'minstock' => 5,
                'discount' => 10,
                'status' => true,
            ],
            [
                'category_id' => $electronics->id,
                'title' => 'Portable Bluetooth Speaker',
                'keywords' => 'speaker, bluetooth, wireless',
                'description' => 'Waterproof outdoor portable Bluetooth speaker',
                'detail' => 'Delivers rich 360-degree sound with powerful bass and up to 20 hours of continuous playtime.',
                'image' => 'products/bluetooth_speaker.png',
                'price' => 79.99,
                'stock' => 60,
                'minstock' => 5,
                'discount' => 0,
                'status' => true,
            ],
            [
                'category_id' => $accessories->id,
                'title' => 'Leather Messenger Bag',
                'keywords' => 'messenger bag, leather, bag, fashion',
                'description' => 'Genuine leather vintage messenger bag',
                'detail' => 'Handcrafted from full-grain leather, featuring a padded laptop compartment and multiple organizer pockets.',
                'image' => 'products/messenger_bag.png',
                'price' => 189.99,
                'stock' => 25,
                'minstock' => 3,
                'discount' => 15,
                'status' => true,
            ],
            [
                'category_id' => $accessories->id,
                'title' => 'Smart Fitness Tracker',
                'keywords' => 'fitness band, smart, health, tracker',
                'description' => 'Waterproof activity and heart rate tracker',
                'detail' => 'Track your steps, heart rate, sleep quality, and active zone minutes with built-in GPS and a vibrant color touchscreen.',
                'image' => 'products/fitness_tracker.png',
                'price' => 99.99,
                'stock' => 40,
                'minstock' => 5,
                'discount' => 5,
                'status' => true,
            ],
            [
                'category_id' => $homeKitchen->id,
                'title' => 'Aesthetic Desk Mat',
                'keywords' => 'desk mat, felt, desk pad, mouse pad',
                'description' => 'Large felt wool desk pad and mouse pad',
                'detail' => 'A premium wool felt desk mat that protects your workspace while offering a smooth, comfortable surface for typing and mouse movements.',
                'image' => 'products/desk_mat.png',
                'price' => 34.99,
                'stock' => 80,
                'minstock' => 10,
                'discount' => 0,
                'status' => true,
            ],
            [
                'category_id' => $homeKitchen->id,
                'title' => 'Smart Water Bottle',
                'keywords' => 'water bottle, smart bottle, kitchen',
                'description' => 'Self-cleaning insulated smart water bottle',
                'detail' => 'Features a built-in UV-C light that purifies water and cleans the bottle interior, keeping drinks cold for 24 hours.',
                'image' => 'products/smart_bottle.png',
                'price' => 59.99,
                'stock' => 45,
                'minstock' => 5,
                'discount' => 10,
                'status' => true,
            ],
            [
                'category_id' => $electronics->id,
                'title' => '4K UHD Home Projector',
                'keywords' => 'projector, home theater, 4k, video',
                'description' => 'Ultra-bright 4K UHD smart home theater projector',
                'detail' => 'Transforms any room into a premium home cinema with stunning 4K visuals, high brightness, and built-in stereo speakers.',
                'image' => 'products/home_projector.png',
                'price' => 699.99,
                'stock' => 12,
                'minstock' => 2,
                'discount' => 20,
                'status' => true,
            ],
            [
                'category_id' => $accessories->id,
                'title' => 'Mechanical Keyboard Wrist Rest',
                'keywords' => 'wrist rest, walnut, keyboard, office',
                'description' => 'Ergonomic solid walnut wood keyboard wrist rest',
                'detail' => 'Made from a single piece of premium walnut wood, providing ergonomic support for long typing sessions.',
                'image' => 'products/wrist_rest.png',
                'price' => 39.99,
                'stock' => 50,
                'minstock' => 5,
                'discount' => 0,
                'status' => true,
            ],
            [
                'category_id' => $homeKitchen->id,
                'title' => 'Minimalist Desk Organizer',
                'keywords' => 'desk organizer, tray, wooden, storage',
                'description' => 'Premium aluminum and wood desktop storage tray',
                'detail' => 'Keep your workspace clutter-free with this stylish desk tray designed to organize pens, phones, and small office supplies.',
                'image' => 'products/desk_organizer.png',
                'price' => 44.99,
                'stock' => 35,
                'minstock' => 5,
                'discount' => 15,
                'status' => true,
            ],
            [
                'category_id' => $homeKitchen->id,
                'title' => 'Aesthetic Desk Lamp',
                'keywords' => 'desk lamp, led, lighting, office',
                'description' => 'Minimalist LED architectural desk lamp',
                'detail' => 'Features a modern, ultra-slim design with adjustable brightness levels and warm light modes to reduce eye strain.',
                'image' => 'products/desk_lamp.png',
                'price' => 89.99,
                'stock' => 30,
                'minstock' => 4,
                'discount' => 5,
                'status' => true,
            ],
        ];

        foreach ($products as $productData) {
            Product::create(array_merge($productData, ['user_id' => $adminUser->id]));
        }

        Slider::create([
            'title' => 'New Season Collection',
            'subtitle' => 'Discover the latest products with amazing deals',
            'button_text' => 'Shop Now',
            'button_link' => '/shop',
            'image' => 'sliders/season_slider.png',
            'sort_order' => 1,
            'status' => true,
        ]);

        Slider::create([
            'title' => 'Up to 50% Off Electronics',
            'subtitle' => 'Limited time offer on all electronics',
            'button_text' => 'Explore Deals',
            'button_link' => '/shop',
            'image' => 'sliders/tech_slider.png',
            'sort_order' => 2,
            'status' => true,
        ]);

        $settings = [
            'site_name' => 'AzuraShop',
            'site_email' => 'contact@azurashop.com',
            'site_phone' => '+90 555 123 4567',
            'site_address' => 'Istanbul, Turkey',
            'currency' => '$',
            'shipping_fee' => '9.99',
            'free_shipping_at' => '100.00',
            'facebook' => 'https://facebook.com',
            'instagram' => 'https://instagram.com',
            'twitter' => 'https://twitter.com',
        ];

        foreach ($settings as $key => $value) {
            Setting::create(['key' => $key, 'value' => $value]);
        }

        Coupon::create([
            'code' => 'AZURA10',
            'type' => 'percent',
            'value' => 10.00,
            'status' => true,
            'expires_at' => now()->addDays(30),
        ]);

        Coupon::create([
            'code' => 'WELCOME20',
            'type' => 'fixed',
            'value' => 20.00,
            'status' => true,
            'expires_at' => now()->addDays(30),
        ]);
    }
}
